@startuml
actor Cliente as C
actor Agente as A

rectangle "Subsistema de Gestão de Pedidos e Contratos" {
    C --> (Cadastrar-se)
    C --> (Gerenciar Pedido de Aluguel) : "Introduzir/Modificar/Consultar/Cancelar"
    
    A --> (Gerenciar Pedido de Aluguel) : "Modificar/Avaliar"
    
    (Gerenciar Pedido de Aluguel) --> (Analisar Pedido Financeiramente)
    
    A --> (Aprovar ou Rejeitar Pedido) 
}

(Analisar Pedido Financeiramente) --> (Aprovar ou Rejeitar Pedido)

@enduml
